//! Generated protobuf types for Angzarr.
//!
//! This module contains all the proto-generated types needed for client
//! applications to interact with Angzarr services.

// Pre-generated proto code - committed to repo for use as library dependency
// To regenerate: `cargo build` with ANGZARR_PROTO_ROOT set, then copy
// target/debug/build/angzarr-client-*/out/angzarr.rs to src/proto/generated.rs
#[path = "generated.rs"]
mod generated;

pub use generated::*;

// NOTE: Example protos (poker domain) moved to angzarr-examples-proto repo
// Business domain protos should be generated by example/client repos
