//! Generated protobuf types for Angzarr.
//!
//! This module contains all the proto-generated types needed for client
//! applications to interact with Angzarr services.
//!
//! Generated via buf CLI from buf.build/angzarr/angzarr.
//! Run `just gen` to regenerate.

mod angzarr {
    include!("gen/angzarr/angzarr.rs");
}

pub use angzarr::*;

// NOTE: Example protos (poker domain) are in buf.build/angzarr/examples
// Business domain protos should be generated by example/client repos
