//! Generated protobuf types for Angzarr.
//!
//! This module contains all the proto-generated types needed for client
//! applications to interact with Angzarr services.

// Include the generated code from tonic_build
tonic::include_proto!("angzarr");

// NOTE: Example protos (poker domain) moved to angzarr-examples-proto repo
// Business domain protos should be generated by example/client repos
